### ISSUE TITLE
need to vendor gopkg.in/yaml.v1

### ISSUE THREAD

**Issue by msuhovec** [ndlib/disadis#1]
The latest binary install of git on our RHEL6 VMs is 1.7.1- very old.

A git server can redirect a client to another git server for content, and it seems that our old git does not support this. So disadis deploys are failing (well, hanging and timing out, technically) when the package
 gopkg.in/yaml.v1, which uses this redirect metadata to serve content from github , is requested.

https://github.com/spf13/hugo/issues/297

Don and I weighed the options. We already vendor content in bendo, and updating git on all our VMs is a lot of work for (at the moment) little-used feature- so vendoring it is!

I have no druthers as to how- godeps or native go (1.5 or later).

**Comment by dbrower** [comment]
I think trying to use the native go toolchain as much as possible is preferable...even if it will require us to use go version 1.5 on all the production machines.

However, i think we will still need a tool like godeps on our development machines to manage the vendered files. (I, for one, do not want to manage that directory by hand).

Link with information: https://github.com/golang/go/wiki/PackageManagementTools#go15vendorexperiment

**Comment by msuhovec** [comment]
OK- I had just finished reading an older document

https://docs.google.com/document/d/1Bz5-UB7g2uPBdOx-rw5t9MxJwkfpx90cqG9AFL0JAYo/edit
